### PR TITLE
this restores the elevation map overlay

### LINKED ISSUE #123: Elevation profile does not work
Enabling the "elevation profile" does not show anything. It should show ASTER GDEM & SRTM Hillshade data.
The reason is that the code pulls from http://korona.geog.uni-heidelberg.de/tiles/asterh/ which does not exist anymore.

### PR DESCRIPTION
**Pull request by wschildbach**
This fixes #123 by using a new server address and addressing scheme.

### CODE REVIEW

**Comment by wschildbach** [comment]
@aAXEe this and all other PRs are ready to go and can be integrated -- fairly easy one-liners most of them. I have a larger PR in the works that massively overhauls the trip planner, but I'd like to get these out of the way first. Thanks :-)

File: index.php [hunk 1]
```diff
@@ -902,12 +902,12 @@ function drawmap() {
 
                 // Elevation Profile
                 layer_elevation_profile_contours = new OpenLayers.Layer.TMS(
-                    'ASTER GDEM Contour Lines (zoom 13-17)',
-                    'http://korona.geog.uni-heidelberg.de/tiles/asterc/?',
+                    'MapSurfer ASTER GDEM contour lines (layer 13-17)',
+                    'http://maps.heigit.org/openmapsurfer/tiles/asterc/webmercator/',
```
Comment (aAXEe) [inline index.php]:
```suggestion
                    'https://maps.heigit.org/openmapsurfer/tiles/asterc/webmercator/',
```

Is there something agains using HTTPS? The map should load as much data as possible via https because it shoudl be served via HTTPS as well.

File: index.php [hunk 2]
```diff
@@ -916,12 +916,12 @@ function drawmap() {
                     }
                 );
                 layer_elevation_profile_hillshade = new OpenLayers.Layer.TMS(
-                    'ASTER GDEM & SRTM Hillshade',
-                    'http://korona.geog.uni-heidelberg.de/tiles/asterh/?',
+                    'Mapsurfer ASTER GDEM and SRTM Hillshade',
+                    'http://maps.heigit.org/openmapsurfer/tiles/asterh/webmercator/',
```
Comment (aAXEe) [inline index.php]:
```suggestion
                    'https://maps.heigit.org/openmapsurfer/tiles/asterh/webmercator/',
```

File: index.php (hunk 1 above)
Comment (wschildbach) [reply index.php]: Good catch. I have checked and https works as well on that server. At least not any worse than http -- I do get a lot of error 503 on that server, it seems a bit overloaded.
